"""
Music genre database with comprehensive electronic music genres.

Includes 50+ genres with feature ranges for classification.
"""

GENRE_DATABASE = {
    "acid": {
        "tempo_range": (120, 140),
        "loudness_range": (0.3, 0.6),
        "spectral_centroid_range": (2000, 5000),
        "zcr_range": (0.08, 0.16),
        "description": "Acid",
        "family": "electronic",
    },
    "acid_house": {
        "tempo_range": (120, 135),
        "loudness_range": (0.35, 0.65),
        "spectral_centroid_range": (2500, 5000),
        "zcr_range": (0.09, 0.17),
        "description": "Acid House",
        "family": "house",
    },
    "acid_jazz": {
        "tempo_range": (80, 130),
        "loudness_range": (0.2, 0.5),
        "spectral_centroid_range": (1500, 3500),
        "zcr_range": (0.05, 0.12),
        "description": "Acid Jazz",
        "family": "jazz",
    },
    "ambient": {
        "tempo_range": (40, 90),
        "loudness_range": (0.05, 0.3),
        "spectral_centroid_range": (1000, 2500),
        "zcr_range": (0.01, 0.05),
        "description": "Ambient",
        "family": "ambient",
    },
    "ambient_breakbeat": {
        "tempo_range": (80, 120),
        "loudness_range": (0.1, 0.4),
        "spectral_centroid_range": (1200, 3000),
        "zcr_range": (0.04, 0.1),
        "description": "Ambient Breakbeat",
        "family": "breakbeat",
    },
    "ambient_house": {
        "tempo_range": (90, 120),
        "loudness_range": (0.15, 0.4),
        "spectral_centroid_range": (1500, 3000),
        "zcr_range": (0.03, 0.08),
        "description": "Ambient House",
        "family": "house",
    },
    "ambient_techno": {
        "tempo_range": (100, 140),
        "loudness_range": (0.2, 0.45),
        "spectral_centroid_range": (1500, 3500),
        "zcr_range": (0.05, 0.11),
        "description": "Ambient Techno",
        "family": "techno",
    },
    "breakbeat": {
        "tempo_range": (140, 180),
        "loudness_range": (0.35, 0.65),
        "spectral_centroid_range": (1500, 4000),
        "zcr_range": (0.08, 0.16),
        "description": "Breakbeat",
        "family": "breakbeat",
    },
    "breakcore": {
        "tempo_range": (160, 200),
        "loudness_range": (0.2, 0.75),
        "spectral_centroid_range": (1500, 4000),
        "zcr_range": (0.08, 0.18),
        "description": "Breakcore/Jungle",
        "family": "breakbeat",
    },
    "club": {
        "tempo_range": (124, 130),
        "loudness_range": (0.35, 0.65),
        "spectral_centroid_range": (2000, 4000),
        "zcr_range": (0.06, 0.13),
        "description": "Club",
        "family": "house",
    },
    "dark_trance": {
        "tempo_range": (130, 150),
        "loudness_range": (0.35, 0.65),
        "spectral_centroid_range": (1500, 3500),
        "zcr_range": (0.07, 0.14),
        "description": "Dark Trance",
        "family": "trance",
    },
    "deep_house": {
        "tempo_range": (110, 130),
        "loudness_range": (0.25, 0.5),
        "spectral_centroid_range": (1500, 3000),
        "zcr_range": (0.04, 0.1),
        "description": "Deep House",
        "family": "house",
    },
    "detroit": {
        "tempo_range": (115, 135),
        "loudness_range": (0.3, 0.6),
        "spectral_centroid_range": (1800, 3500),
        "zcr_range": (0.06, 0.13),
        "description": "Detroit Techno",
        "family": "techno",
    },
    "downtempo": {
        "tempo_range": (85, 115),
        "loudness_range": (0.15, 0.4),
        "spectral_centroid_range": (1200, 2800),
        "zcr_range": (0.03, 0.09),
        "description": "Downbeat/Downtempo",
        "family": "ambient",
    },
    "drum_bass": {
        "tempo_range": (160, 180),
        "loudness_range": (0.35, 0.65),
        "spectral_centroid_range": (2000, 4000),
        "zcr_range": (0.08, 0.14),
        "description": "Drum & Bass",
        "family": "breakbeat",
    },
    "dub": {
        "tempo_range": (80, 110),
        "loudness_range": (0.25, 0.5),
        "spectral_centroid_range": (500, 2000),
        "zcr_range": (0.02, 0.08),
        "description": "Dub",
        "family": "reggae",
    },
    "dubstep": {
        "tempo_range": (135, 150),
        "loudness_range": (0.4, 0.7),
        "spectral_centroid_range": (1000, 3500),
        "zcr_range": (0.1, 0.18),
        "description": "Dubstep",
        "family": "electronic",
    },
    "edm": {
        "tempo_range": (120, 150),
        "loudness_range": (0.4, 0.75),
        "spectral_centroid_range": (2000, 5000),
        "zcr_range": (0.07, 0.15),
        "description": "EDM",
        "family": "electronic",
    },
    "electro": {
        "tempo_range": (110, 140),
        "loudness_range": (0.35, 0.65),
        "spectral_centroid_range": (2000, 4500),
        "zcr_range": (0.08, 0.16),
        "description": "Electro",
        "family": "electronic",
    },
    "electronic": {
        "tempo_range": (100, 160),
        "loudness_range": (0.3, 0.65),
        "spectral_centroid_range": (2000, 5000),
        "zcr_range": (0.05, 0.16),
        "description": "Electronic",
        "family": "electronic",
    },
    "euro_dance": {
        "tempo_range": (130, 145),
        "loudness_range": (0.4, 0.7),
        "spectral_centroid_range": (2000, 4500),
        "zcr_range": (0.07, 0.15),
        "description": "Euro-Dance",
        "family": "dance",
    },
    "euro_rave": {
        "tempo_range": (150, 180),
        "loudness_range": (0.4, 0.75),
        "spectral_centroid_range": (2000, 4500),
        "zcr_range": (0.09, 0.17),
        "description": "Euro-Rave",
        "family": "rave",
    },
    "future_house": {
        "tempo_range": (115, 135),
        "loudness_range": (0.35, 0.6),
        "spectral_centroid_range": (2000, 4000),
        "zcr_range": (0.06, 0.12),
        "description": "Future House",
        "family": "house",
    },
    "future_bass": {
        "tempo_range": (100, 140),
        "loudness_range": (0.3, 0.6),
        "spectral_centroid_range": (2000, 4500),
        "zcr_range": (0.06, 0.13),
        "description": "Future Bass",
        "family": "electronic",
    },
    "gabber": {
        "tempo_range": (170, 200),
        "loudness_range": (0.5, 0.8),
        "spectral_centroid_range": (2000, 4500),
        "zcr_range": (0.1, 0.18),
        "description": "Gabber",
        "family": "hardcore",
    },
    "garage": {
        "tempo_range": (115, 135),
        "loudness_range": (0.3, 0.55),
        "spectral_centroid_range": (1800, 3500),
        "zcr_range": (0.07, 0.14),
        "description": "Garage",
        "family": "house",
    },
    "goa": {
        "tempo_range": (130, 150),
        "loudness_range": (0.35, 0.65),
        "spectral_centroid_range": (2000, 4000),
        "zcr_range": (0.08, 0.15),
        "description": "Goa",
        "family": "trance",
    },
    "goa_trance": {
        "tempo_range": (135, 155),
        "loudness_range": (0.35, 0.65),
        "spectral_centroid_range": (2000, 4000),
        "zcr_range": (0.08, 0.15),
        "description": "Goa Trance",
        "family": "trance",
    },
    "happy_hardcore": {
        "tempo_range": (150, 180),
        "loudness_range": (0.45, 0.75),
        "spectral_centroid_range": (2500, 5000),
        "zcr_range": (0.1, 0.18),
        "description": "Happy Hardcore",
        "family": "hardcore",
    },
    "hardcore": {
        "tempo_range": (160, 190),
        "loudness_range": (0.45, 0.75),
        "spectral_centroid_range": (2000, 4500),
        "zcr_range": (0.1, 0.18),
        "description": "Hardcore",
        "family": "hardcore",
    },
    "hard_trance": {
        "tempo_range": (140, 160),
        "loudness_range": (0.4, 0.7),
        "spectral_centroid_range": (2000, 4500),
        "zcr_range": (0.08, 0.15),
        "description": "Hard Trance",
        "family": "trance",
    },
    "house": {
        "tempo_range": (115, 135),
        "loudness_range": (0.3, 0.6),
        "spectral_centroid_range": (2000, 4000),
        "zcr_range": (0.06, 0.13),
        "description": "House",
        "family": "house",
    },
    "idm": {
        "tempo_range": (90, 140),
        "loudness_range": (0.2, 0.5),
        "spectral_centroid_range": (1500, 3500),
        "zcr_range": (0.05, 0.13),
        "description": "IDM",
        "family": "electronic",
    },
    "industrial": {
        "tempo_range": (90, 150),
        "loudness_range": (0.35, 0.7),
        "spectral_centroid_range": (1500, 4000),
        "zcr_range": (0.08, 0.16),
        "description": "Industrial",
        "family": "industrial",
    },
    "jungle": {
        "tempo_range": (155, 180),
        "loudness_range": (0.3, 0.65),
        "spectral_centroid_range": (1500, 4000),
        "zcr_range": (0.08, 0.16),
        "description": "Jungle",
        "family": "breakbeat",
    },
    "minimal": {
        "tempo_range": (120, 140),
        "loudness_range": (0.25, 0.5),
        "spectral_centroid_range": (1500, 3000),
        "zcr_range": (0.04, 0.1),
        "description": "Minimal Techno",
        "family": "techno",
    },
    "minimal_trance": {
        "tempo_range": (125, 145),
        "loudness_range": (0.3, 0.55),
        "spectral_centroid_range": (1500, 3500),
        "zcr_range": (0.06, 0.12),
        "description": "Minimal Trance",
        "family": "trance",
    },
    "progressive_house": {
        "tempo_range": (120, 140),
        "loudness_range": (0.3, 0.6),
        "spectral_centroid_range": (2000, 4000),
        "zcr_range": (0.06, 0.13),
        "description": "Progressive House",
        "family": "house",
    },
    "progressive_trance": {
        "tempo_range": (130, 150),
        "loudness_range": (0.35, 0.65),
        "spectral_centroid_range": (2000, 4000),
        "zcr_range": (0.07, 0.14),
        "description": "Progressive Trance",
        "family": "trance",
    },
    "psytrance": {
        "tempo_range": (135, 155),
        "loudness_range": (0.35, 0.65),
        "spectral_centroid_range": (1800, 4000),
        "zcr_range": (0.08, 0.15),
        "description": "Psytrance",
        "family": "trance",
    },
    "rave": {
        "tempo_range": (140, 170),
        "loudness_range": (0.4, 0.7),
        "spectral_centroid_range": (2000, 4500),
        "zcr_range": (0.08, 0.16),
        "description": "Rave",
        "family": "rave",
    },
    "tech_house": {
        "tempo_range": (120, 130),
        "loudness_range": (0.3, 0.55),
        "spectral_centroid_range": (1800, 3500),
        "zcr_range": (0.06, 0.12),
        "description": "Tech House",
        "family": "house",
    },
    "techno": {
        "tempo_range": (120, 150),
        "loudness_range": (0.3, 0.65),
        "spectral_centroid_range": (1500, 4000),
        "zcr_range": (0.06, 0.14),
        "description": "Techno",
        "family": "techno",
    },
    "trance": {
        "tempo_range": (130, 150),
        "loudness_range": (0.35, 0.65),
        "spectral_centroid_range": (2000, 4000),
        "zcr_range": (0.07, 0.14),
        "description": "Trance",
        "family": "trance",
    },
    "trip_hop": {
        "tempo_range": (85, 120),
        "loudness_range": (0.25, 0.5),
        "spectral_centroid_range": (1500, 3500),
        "zcr_range": (0.05, 0.12),
        "description": "Trip Hop",
        "family": "hip_hop",
    },
}
